// Generated by CoffeeScript 1.8.0
var app, bodyParser, cookieParser, engine, express, favicon, http, io, logger, path, routes_index, server;

express = require('express');

path = require('path');

favicon = require('serve-favicon');

logger = require('morgan');

cookieParser = require('cookie-parser');

bodyParser = require('body-parser');

http = require('http');

engine = require('ect');

app = express();

server = http.createServer(app);

server.listen(3000, '127.0.0.1');

console.log('Server Start. (:3000)');

io = require('socket.io').listen(server);

app.use(logger('dev'));

app.use(bodyParser.json());

app.use(bodyParser.urlencoded({
  extended: false
}));

app.use(cookieParser());

app.use(express["static"](path.join(__dirname, 'public')));

app.use(express["static"](__dirname + '/public'));

app.set('view engine', 'ect');

app.engine('ect', engine({
  watch: true,
  root: __dirname + '/views',
  ext: '.ect'
}).render);

routes_index = require('./routes/index');

app.get('/', routes_index.root);

io.on('connection', function(socket) {
  socket.on('emit', function(data) {
    console.log('in comming.');
  });
});
